small reafactoring of printing and clean up

diff --git a/test/run_coverage_tests b/test/run_coverage_tests
--- a/test/run_coverage_tests
+++ b/test/run_coverage_tests
@@ -6,16 +6,39 @@ print_headline() {
     printf "###################\n"
 }
 
+coverage_file=".coverage"
+if [ -e $coverage_file ]; then
+    rm $coverage_file
+fi
 
-print_headline "Running unit tests"
+no_nose=0
+while getopts ":n" opt; do
+  case $opt in
+    n)
+      no_nose=1
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
 
-COVERAGE_FILE=".coverage.nose" nosetests --with-coverage --cover-package=.
+
+if [ $no_nose -ne 1 ]; then
+    print_headline "Running unit tests"
+    COVERAGE_FILE=".coverage.nose" nosetests --with-coverage --cover-package=.
+fi
 
 print_headline "Running functional tests"
 export COVERAGE="coverage run -a"
 COVERAGE_FILE=".coverage.roundup" roundup test/doto-cli-test.sh
 
-print_headline "Running functional tests"
+print_headline "Results"
 unset COVERAGE
 coverage combine
 coverage report --show-missing --fail-under=90
